backend:
  name: github
  repo: omsaritainfotech-star/cognition-classes-site
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "courses"
    label: "Courses"
    folder: "content/courses"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string", default: "Software Dev" }
      - { label: "Duration", name: "duration", widget: "string", default: "3 months" }
      - { label: "Fee", name: "fee", widget: "string", default: "₹—" }
      - { label: "Next Batch", name: "nextBatch", widget: "string", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Mode", name: "mode", widget: "select", options: ["Online", "Offline"], default: "Online" }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    identifier_field: "name"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Course", name: "course", widget: "string", required: false }
      - { label: "Quote", name: "quote", widget: "text" }

  - name: "results"
    label: "Results & Selections"
    folder: "content/results"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Student Name", name: "studentName", widget: "string" }
      - { label: "Exam", name: "exam", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Score/Rank", name: "score", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
